name: company_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  rxdart: ^0.27.7
  timezone: ^0.9.2
  ionicons: ^0.2.2
  freezed_annotation: ^2.4.1
  connectivity_plus: ^2.3.8
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
